# --topic_cam0=/dvs/image_raw
--topic_dvs0=/event_camera/events
--topic_imu0=/event_camera/imu
# --topic_dvs0=/dvx/events
# --topic_imu0=/dvx/imu

--imp_detector_grid_size=32
--imp_detector_name=FAST
--imp_detector_border_margin=5
--imp_detector_threshold=50
--vio_descriptor_use_dummy=True

# tracking
--vio_kfselect_numfts_lower_thresh=30
--vio_add_every_nth_frame_to_backend=1
--vio_feature_tracker_patch_size_by8=6,4
--imp_detector_max_features_per_frame=200

--vio_feature_tracker_termcrit_min_update_squared=0.1

--vio_viz_level=0
--vio_viz_skip_rate=1

# imu bias override
--vio_acc_bias_init_x=0.870743440440167
--vio_acc_bias_init_y=-0.7136510658018353
--vio_acc_bias_init_z=0.7110535922063379
--vio_gyr_bias_init_x=-0.002029665288470071
--vio_gyr_bias_init_y=-0.002077271159761909
--vio_gyr_bias_init_z=0.005243611304158206

# resting imu values
# --vio_acc_bias_init_x=0.7197085022926331
# --vio_acc_bias_init_y=-10.437569618225098
# --vio_acc_bias_init_z=0.3436877429485321
# --vio_gyr_bias_init_x=-0.0018642125651240349
# --vio_gyr_bias_init_y=-0.002929477021098137
# --vio_gyr_bias_init_z=0.004261057358235121


